app-shortname: student
server:
  port: 8001
#???????
spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://127.0.0.1:3306/wy_practice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: ${app-shortname}

  profiles:
    include: logging-${spring.profiles.active}
    active: dev

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false #????????????



